services:
  - type: web
    name: shopease-final
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: cd backend && node server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false # Important: user must paste their real MongoDB Atlas URI here
      - key: JWT_SECRET
        generateValue: true
      - key: ENCRYPTION_KEY
        generateValue: true
      - key: ADMIN_EMAIL
        value: kotareddy9848@gmail.com
      - key: ADMIN_PASSWORD
        value: kotareddy9848
      - key: ADMIN_NAME
        value: Admin
      - key: STRIPE_SECRET_KEY
        sync: false # User should update this for real payments
